#!/bin/bash

set -e # Stop executing if anything goes wrong

failed_hosts=();

for host in $(cat $1/agents.txt); do
  echo "Attempting to connect to $host..."
  if ssh -q -o ConnectTimeout=3 -o BatchMode=yes $host << 'EOF'

  cd /tmp

  wget --quiet https://github.com/neuroDEVergent/cubes-zabbix-custom/archive/refs/heads/main.tar.gz
  tar -xzf main.tar.gz
  rm main.tar.gz

  cd cubes-zabbix-custom-main/
  chmod +x deploy-agent-conf;
  chmod +x deploy-agent-scripts;

  ./deploy-agent-conf $1
  ./deploy-agent-scripts $1

  cd ..
  rm -rf /tmp/cubes-zabbix-custom-main
  exit

EOF
 then
  echo ""
  echo "Finished working on $host"
  echo ""

else
  echo "Connection to $host failed"
  failed_hosts+=("$host");
fi;
done;

echo ""
echo "Connection failed for following hosts:"
printf '%s\n' "${failed_hosts[@]}"
