#!/bin/bash

# It doesn't matter where the script is executed from, it's always as if we are invoking it from script's directory
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

zbx_restart_flag=0

# Compare returns 0 if files are the same, so we skip install and reset if it's unecessary
echo "-----"
echo "Installing scripts...";
echo ""

for file in ../$1/scripts/*; do
	current_file="${file##*/}";
	echo "Installing $current_file...";

	echo "Checking if script exists and / or needs to be updated...";
	if ! cmp -s ../$1/scripts/$current_file /usr/local/bin/$current_file; then
		echo "Files are not the same!";
		echo "Installing / Updating the script..."

		if install -D --owner root --group zabbix -m 750 ../$1/scripts/$current_file /usr/local/bin/$current_file; then
			echo "Script updated successfully!";
			zbx_restart_flag=1;
		else
			echo "Failed to update the script";
		fi
		
	else
		echo "File already exists!";
		echo "Skipping..."
	fi

done;

if [[ $zbx_restart_flag -ne 0 ]]; then
	echo "Restarting zabbix-agent.service..."
	if systemctl restart zabbix-agent.service; then
		echo "Zabbix service restarted successfully!";
	else
		echo "Zabbix service failed to restart.";
	fi
fi

echo "Done!"
echo "Exiting program..."
