#!/bin/bash

findmnt --fstab --output TARGET --noheadings |
grep -vE '^/(boot|boot/efi|media/cdrom.*|proc|sys|dev|run|var/cache/nginx|)$' |
while read -r target; do

    [ "$target" = "none" ] && continue

    if ! findmnt "$target" >/dev/null; then
        echo "$target"
    fi

done
